version: '3.9'
services:
  palworld-server:
    #build: .
    image: 'charliejadek/palworld-arm64-dedicated-server:latest'
    container_name: 'palworld-server'
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    env_file:
      - ./default.env
    restart: 'unless-stopped'
    volumes:
      - './game:/palworld'
